import Foundation

enum Loc {
    static func t(_ key: String) -> String {
        let lang = AppSettings.currentLanguageCode
        return (lang == "ar" ? ar[key] : en[key]) ?? key
    }

    static func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), arguments: args)
    }

    static let ar: [String: String] = [
        "app_name": "ذكّي",
        "welcome_title": "أهلًا بك في ذكّي",
        "welcome_subtitle": "منصة مذاكرة جماعية بمساعدة الذكاء الاصطناعي",
        "login": "تسجيل الدخول",
        "signup": "إنشاء حساب",
        "continue_guest": "استمر بدون حساب",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "username": "الاسم",
        "education_level": "المرحلة الدراسية",
        "proficiency_level": "المستوى",
        "already_have_account": "عندك حساب؟",
        "no_account": "ما عندك حساب؟",
        "home": "الرئيسية",
        "rooms": "الغرف",
        "library": "المكتبة",
        "performance": "أدائي",
        "settings": "الإعدادات",
        "upload_pdf": "ارفع ملف PDF",
        "upload_pdf_subtitle": "ابدأ مذاكرة فردية من ملف جديد",
        "solo_study": "مذاكرة فردية",
        "group_room": "غرفة جماعية",
        "group_room_subtitle": "ادرس مع زملائك بغرفة مباشرة",
        "live_lesson_subtitle": "سبورة وصوت جماعي حي مع طلابك",
        "room_type_classroom": "درس مباشر",
        "room_type_quiz": "غرفة جماعية",
        "summary": "الملخص",
        "quiz": "الاختبار",
        "chat_assistant": "اسأل ذكّي",
        "login_required_for_rooms": "لازم تسجل الدخول عشان تدخل درس مباشر أو جلسة جماعية",
        "create_room": "أنشئ غرفة",
        "join_room": "عندي كود",
        "room_code": "كود الغرفة",
        "your_name": "اسمك",
        "logout": "تسجيل خروج",
        "language": "اللغة",
        "appearance": "المظهر",
        "appearance_system": "تلقائي",
        "appearance_light": "فاتح",
        "appearance_dark": "داكن",
        "subscription": "الاشتراك",
        "subscription_subtitle": "إدارة باقتك واشتراكك",
        "friends": "الأصدقاء",
        "friends_subtitle": "أضف أصدقاء وشوف طلبات الصداقة",
        "archive": "الأرشيف",
        "archive_subtitle": "جلسات المذاكرة الجماعية السابقة",
        "notes": "ملاحظاتي",
        "notes_subtitle": "دفتر ملاحظاتك الشخصي",
        "notes_search_placeholder": "ابحث بالملاحظات...",
        "notes_new": "ملاحظة جديدة",
        "notes_empty": "ما فيه ملاحظات هنا لحد الحين",
        "notes_folder_all": "الكل",
        "notes_folder_unfiled": "بدون مجلد",
        "notes_new_folder": "مجلد جديد",
        "notes_folder_name_placeholder": "اسم المجلد",
        "notes_untitled": "بدون عنوان",
        "notes_delete_confirm": "تحذف هذي الملاحظة نهائيًا؟",
        "notes_delete_folder_confirm": "تحذف هذا المجلد؟ الملاحظات جواه تبقى بدون مجلد",
        "note_type_text": "نص",
        "note_type_checklist": "قائمة المهام",
        "note_title_placeholder": "عنوان الملاحظة",
        "note_content_placeholder": "اكتب ملاحظتك هنا...",
        "note_checklist_add_placeholder": "إضافة عنصر...",
        "note_folder_label": "المجلد",
        "note_pin": "تثبيت",
        "note_unpin": "إلغاء التثبيت",
        "ai_assistant": "المساعد الذكي",
        "ai_assistant_subtitle": "سولف مع ذكيّ أو خله يلخّص لك كتاب",
        "ai_conversations_empty": "ما فيه محادثات لحد الحين - ابدأ وحدة جديدة!",
        "ai_new_conversation_title": "محادثة جديدة",
        "ai_empty_conversation": "اسأل ذكّي أي شي، أو لخّص كتاب بزر الكتاب تحت",
        "ai_message_placeholder": "اكتب رسالتك...",
        "ai_summarize_book": "لخّص كتاب",
        "ai_source_library": "من مكتبتك",
        "ai_source_upload": "ارفع ملف",
        "ai_upload_hint": "ارفع ملف PDF وذكيّ يلخّصه لك",
        "ai_pick_file": "اختر ملف PDF",
        "assignments": "الواجبات",
        "assignments_subtitle": "واجباتك وحلولها",
        "assignments_heading": "دفتر الواجبات",
        "assignment_new_heading": "واجب جديد",
        "assignment_class_label": "الفصل",
        "assignment_subject_placeholder": "اسم المادة",
        "assignment_title_placeholder": "عنوان الواجب",
        "assignment_content_placeholder": "محتوى الواجب",
        "btn_create_assignment": "إنشاء الواجب",
        "assignments_empty": "ما فيه واجبات لحد الحين",
        "assignment_status_pending": "لم يُحل بعد",
        "assignment_status_done": "تم الحل",
        "assignment_submitted_count": "%d/%d سلّموا",
        "assignment_submit_heading": "حل الواجب",
        "btn_pick_assignment_file": "اختر ملف الحل",
        "assignment_note_placeholder": "ملاحظة (اختياري)",
        "btn_submit_assignment": "تسليم الواجب",
        "assignment_students_heading": "حالة التسليم",
        "assignment_grade_label": "الدرجة",
        "btn_save_grade": "حفظ الدرجة",
        "btn_view_file": "عرض الملف",
        "assignment_no_students": "ما فيه طلاب بهذا الفصل بعد",
        "assignment_submitted_file_label": "الملف المُسلَّم: %@",
        "assignment_note_shown": "ملاحظتك: %@",
        "assignment_grade_shown": "الدرجة: %@",
        "assignment_not_graded_yet": "لسا ما تصحح",
        "err_assignment_need_class": "لازم تختار الفصل",

        "quizzes": "الاختبارات",
        "quizzes_subtitle": "اختبارات مادتك ودرجاتها",
        "quizzes_heading": "الاختبارات",
        "quizzes_empty": "ما فيه اختبارات لحد الحين",
        "quiz_new_heading": "اختبار جديد",
        "quiz_edit_heading": "تعديل الاختبار",
        "quiz_class_label": "الفصل",
        "quiz_subject_placeholder": "اسم المادة",
        "quiz_title_placeholder": "عنوان الاختبار",
        "quiz_time_limit_stepper_label": "مدة الاختبار: %d دقيقة",
        "quiz_time_limit_minutes_format": "%d دقيقة",
        "quiz_questions_heading": "الأسئلة",
        "btn_add_question": "إضافة سؤال",
        "quiz_question_type_label": "نوع السؤال",
        "quiz_type_mcq": "اختيارات",
        "quiz_type_true_false": "صح وخطأ",
        "quiz_type_essay": "مقالي",
        "quiz_question_text_placeholder": "نص السؤال",
        "btn_add_choice": "إضافة اختيار",
        "quiz_choice_placeholder": "الاختيار %d",
        "quiz_mark_correct_hint": "اختر الإجابة الصحيحة (اختياري)",
        "quiz_true_label": "صح",
        "quiz_false_label": "خطأ",
        "btn_create_quiz": "إنشاء الاختبار",
        "btn_save_changes": "حفظ التعديلات",
        "err_quiz_need_class": "لازم تختار الفصل",
        "err_quiz_need_question": "لازم تضيف سؤال واحد على الأقل بنص",
        "quiz_status_draft": "مسودة",
        "quiz_status_published": "منشور",
        "quiz_status_not_taken": "لم يُحل بعد",
        "quiz_submitted_count": "%d/%d سلّموا",
        "btn_publish_quiz": "نشر الاختبار",
        "quiz_publish_confirm_title": "نشر الاختبار",
        "quiz_publish_confirm_message": "بعد النشر ما تقدر تعدّل الاختبار أو تحذفه. تبي تنشره؟",
        "quiz_delete_confirm_title": "حذف الاختبار",
        "quiz_delete_confirm_message": "متأكد إنك تبي تحذف هالاختبار؟",
        "quiz_students_heading": "حالة الطلاب",
        "quiz_no_students": "ما فيه طلاب بهذا الفصل بعد",
        "quiz_view_answers": "عرض الإجابات",
        "quiz_hide_answers": "إخفاء الإجابات",
        "quiz_correct_answer_label": "الإجابة الصحيحة: %@",
        "quiz_student_answer_label": "إجابة الطالب: %@",
        "quiz_no_answer": "بدون إجابة",
        "quiz_auto_submitted_badge": "تسليم تلقائي (انتهى الوقت)",
        "quiz_time_remaining_label": "الوقت المتبقي: %@",
        "btn_submit_quiz": "تسليم الاختبار",
        "quiz_submit_confirm_title": "تسليم الاختبار",
        "quiz_submit_confirm_message": "متأكد إنك تبي تسلّم إجاباتك؟",
        "quiz_result_graded_heading": "نتيجتك",
        "quiz_result_grade_format": "الدرجة: %@",
        "quiz_awaiting_grade": "بانتظار التصحيح",
        "quiz_result_awaiting_message": "تم تسليم إجاباتك، بانتظار تصحيح المعلم",
        "quiz_result_auto_submitted_message": "انتهى الوقت وتم تسليم إجاباتك تلقائيًا",
        "quiz_essay_answer_placeholder": "اكتب إجابتك هنا",
        // ---- مدرستي: اختصار الموقع الرسمي + أدوات ذكيّ المستقلة (أي حساب مسجّل دخول) ----
        "nav_madrasati": "مدرستي",
        "madrasati_nav_subtitle": "اختصار مدرستي + أدوات ذكيّ للمعلم والطالب",
        "madrasati_heading": "مدرستي وأدوات ذكيّ للمعلم",
        "madrasati_desc": "اختصار سريع لموقع مدرستي الرسمي، بالإضافة لأدوات ذكيّ الذكية للمعلمين - مستقلة تمامًا عن مدرستي وما تشارك أي بيانات وياها.",
        "madrasati_link_desc": "يفتح موقع مدرستي الرسمي بتبويب جديد - تسجّل دخولك مباشرة عندهم، وذكيّ ما يشوف ولا يلمس بيانات حسابك هناك إطلاقًا.",
        "btn_open_madrasati": "🔗 افتح مدرستي الرسمي",
        "teacher_tools_heading": "👨‍🏫 أدوات ذكيّ للمعلم",
        "btn_new_lesson_prep": "➕ تحضير جديد بالذكاء الاصطناعي",
        "btn_open_enrichment": "🌟 نشاط إثرائي",
        "btn_open_results_analysis": "📊 تحليل نتائج الطلاب",
        "saved_lesson_preps_heading": "📁 تحضيراتي المحفوظة",
        "lesson_prep_empty": "ما فيه تحضيرات محفوظة بعد.",
        "student_tools_heading": "🎒 أدوات ذكيّ للطالب",
        "btn_new_homework_help": "➕ مساعد واجب جديد",
        "btn_new_study_plan": "🗓️ خطة مذاكرة جديدة",
        "saved_homework_help_heading": "📁 جلسات مساعد الواجب المحفوظة",
        "homework_help_empty": "ما فيه جلسات محفوظة بعد.",
        "saved_study_plans_heading": "📁 خطط المذاكرة المحفوظة",
        "study_plan_empty": "ما فيه خطط محفوظة بعد.",

        "lesson_prep_create_heading": "تحضير درس جديد",
        "lesson_prep_view_heading": "تحضير الدرس",
        "ph_lesson_prep_subject": "اسم المادة",
        "ph_lesson_prep_grade": "الصف",
        "ph_lesson_prep_unit": "الوحدة (اختياري)",
        "ph_lesson_prep_title": "عنوان الدرس",
        "btn_generate_lesson_prep": "✨ ولّد التحضير",
        "err_lesson_prep_fields_required": "لازم المادة والصف وعنوان الدرس",
        "err_lesson_prep_gen_failed": "تعذّر توليد التحضير، حاول مرة ثانية",
        "lp_objectives_label": "🎯 الأهداف التعلّمية",
        "lp_intro_label": "🚪 التمهيد",
        "lp_steps_label": "📋 خطوات التنفيذ",
        "lp_activities_label": "🎲 الأنشطة الصفية",
        "lp_assessment_label": "📊 التقويم",
        "lp_homework_label": "📝 الواجب",
        "lp_enrichment_label": "🌟 الإثراء",
        "btn_save_lesson_prep": "💾 حفظ التحضير",
        "btn_copy_lesson_prep": "📋 نسخ التحضير",
        "btn_regenerate_lesson_prep": "🔄 توليد من جديد",
        "btn_delete_lesson_prep": "🗑️ حذف",
        "copied_label": "✅ تم النسخ",
        "saved_label": "✅ تم الحفظ",
        "err_copy_failed": "تعذّر النسخ",
        "confirm_delete_lesson_prep": "تحذف هذا التحضير نهائيًا؟",

        "enrichment_heading": "مولّد نشاط إثرائي",
        "enrichment_desc": "اكتب المادة والصف والموضوع، وذكيّ يقترح نشاط إثرائي جاهز للطلاب المتفوقين.",
        "ph_topic": "الموضوع",
        "btn_generate_enrichment": "✨ ولّد النشاط",

        "results_analysis_heading": "محلّل نتائج الطلاب",
        "results_analysis_desc": "الصق درجات/نتائج طلابك بأي صيغة (أسماء ودرجات)، وذكيّ يحلّلها ويطلّع لك نقاط القوة والضعف والطلاب المحتاجين متابعة.",
        "ph_raw_results": "مثال:\nأحمد: 18/20\nسارة: 12/20",
        "btn_generate_results_analysis": "✨ حلّل النتائج",
        "err_raw_results_required": "لازم تلصق نتائج الطلاب",
        "ra_summary_label": "📝 ملخص عام",
        "ra_strengths_label": "💪 نقاط القوة",
        "ra_weaknesses_label": "⚠️ نقاط الضعف",
        "ra_at_risk_label": "🚨 يحتاجون متابعة",
        "ra_recommendations_label": "✅ توصيات",

        "homework_help_create_heading": "مساعد واجب جديد",
        "homework_help_view_heading": "مساعد الواجب",
        "ph_homework_topic": "الموضوع أو سؤال الواجب",
        "btn_generate_homework_help": "✨ ساعدني",
        "btn_save_homework_help": "💾 حفظ",
        "confirm_delete_homework_help": "تحذف جلسة مساعد الواجب هذي نهائيًا؟",
        "hh_explanation_label": "💡 الشرح",
        "hh_example_label": "📐 مثال محلول",
        "hh_practice_label": "✏️ أسئلة تدريبية",
        "hh_tips_label": "💡 نصيحة",

        "study_plan_create_heading": "خطة مذاكرة جديدة",
        "study_plan_view_heading": "خطة المذاكرة",
        "ph_study_plan_subjects": "المواد (افصل بينها بفاصلة)",
        "ph_study_plan_hours": "ساعات المذاكرة يوميًا (اختياري)",
        "study_plan_exam_date_toggle": "أضف تاريخ الاختبار",
        "study_plan_exam_date_label": "تاريخ الاختبار",
        "btn_generate_study_plan": "✨ ولّد الخطة",
        "btn_save_study_plan": "💾 حفظ",
        "err_study_plan_subjects_required": "لازم تكتب المواد اللي تبي تذاكرها",
        "confirm_delete_study_plan": "تحذف خطة المذاكرة هذي نهائيًا؟",
        "sp_tips_label": "💡 نصائح عامة",

        "current_plan": "باقتك الحالية",
        "free_plan": "مجاني",
        "greeting_prefix": "أهلًا، %@",
        "home_greeting_subtitle": "جاهز تذاكر اليوم؟",
        "default_student_name": "طالب",
        "loading": "يحمّل...",
        "error_generic": "صار خطأ، جرب مرة ثانية",
        "err_unexpected_response": "رد غير متوقع من الخادم",
        "err_server_status": "خطأ من الخادم (%d)",
        "ok": "حسنًا",
        "cancel": "إلغاء",
        "save": "حفظ",
        "add": "إضافة",
        "search": "بحث",
        "delete": "حذف",
        "rename": "إعادة تسمية",
        "edit": "تعديل",
        "next": "التالي",
        "finish": "إنهاء",
        "library_guest_gate": "سجل دخول عشان تشوف مكتبتك",
        "library_empty": "ما فيه كتب محفوظة بعد",
        "library_pick_empty": "ما فيه كتب بمكتبتك بعد - احفظ ملف من المذاكرة الفردية أول",
        "pick_from_library": "اختر من مكتبتك",
        "add_book": "أضف كتاب",
        "upload_from_device": "ارفع من جهازك",
        "rename_book_title": "إعادة تسمية الكتاب",
        "book_title_placeholder": "اسم الكتاب",
        "confirm_delete_book": "متأكد تبي تحذف هذا الكتاب من مكتبتك؟",
        "save_to_library_title": "احفظ بمكتبتك",
        "library_count_label": "%d كتاب بالمكتبة",
        "open_for_study": "افتح للمذاكرة",
        "archive_guest_gate": "سجل دخول عشان تشوف أرشيفك",
        "archive_empty": "ما فيه جلسات جماعية أو دروس بأرشيفك لحد الحين",
        "archive_host_label": "المضيف: %@",
        "friends_guest_gate": "سجل دخول عشان تضيف أصدقاء",
        "friends_empty": "ما عندك أصدقاء بعد",
        "my_friends": "أصدقائي",
        "friends_count_label": "%d صديق",
        "add_friend_section": "إضافة صديق",
        "search_username_placeholder": "ابحث باسم المستخدم",
        "incoming_requests": "طلبات واردة",
        "outgoing_requests": "طلبات مرسلة",
        "pending_label": "قيد الانتظار",
        "accept": "قبول",
        "reject": "رفض",
        "remove_friend": "حذف",
        "confirm_remove_friend": "متأكد تبي تحذف هذا الصديق؟",
        "my_qr_code": "رمز QR الخاص فيك",
        "scan_qr": "امسح رمز QR",
        "join_room_qr": "رمز دخول الغرفة",
        "session_invites_heading": "📩 دعوات جلسات",
        "session_invites_empty": "ما فيه دعوات جديدة",
        "invite_from_prefix": "دعوة من %@",
        "btn_join_now": "انضم الآن",
        "btn_dismiss_invite": "تجاهل",
        "profile": "البروفايل",
        "my_profile": "بروفايلي",
        "my_profile_subtitle": "نبذة، مدرستك، وخصوصية بياناتك",
        "private_profile_badge": "خاص",
        "private_profile_notice": "هذا البروفايل خاص - ما يقدر يشوف تفاصيله غير صاحبه",
        "already_friends_badge": "صديقك بالفعل",
        "incoming_request_notice": "أرسل لك طلب صداقة - تقدر تقبله من شاشة الأصدقاء",
        "add_friend_button": "أضف صديق",
        "stat_attempts": "محاولات",
        "stat_avg_score": "متوسط الدرجات",
        "stat_study_minutes": "دقائق مذاكرة",
        "stat_streak": "أيام متتالية",
        "profile_bio_section": "نبذة عنك",
        "profile_bio_placeholder": "اكتب نبذة بسيطة عنك...",
        "school_name_placeholder": "اسم مدرستك",
        "private_profile_toggle": "خلي بروفايلي خاص بالكامل",
        "private_profile_footer": "لو فعّلته، محد يقدر يشوف أي شي بروفايلك غير اسمك، حتى لو كان صديقك.",
        "profile_sections_visibility_heading": "يظهر بالبروفايل العام",
        "guest_mode_label": "وضع الضيف",
        "not_logged_in_label": "ما سجلت دخول",
        "edit_profile": "تعديل البيانات",
        "edit_profile_subtitle": "الاسم، رقم الجوال، وكلمة المرور",
        "phone_number": "رقم الجوال",
        "new_password": "كلمة المرور الجديدة",
        "update_password": "تحديث كلمة المرور",
        "profile_updated": "تم تحديث البيانات ✓",
        "password_updated": "تم تحديث كلمة المرور ✓",
        "start_study_button": "ابدأ مذاكرة",
        "start_quiz_button": "ابدأ اختبار",
        "start_quiz_final_button": "ابدأ الاختبار للجميع",
        "step_pick_file_title": "اختيار ملف",
        "step_summary_title": "الملخص",
        "step_quiz_title": "الاختبار",
        "next_generate_quiz": "التالي: توليد الاختبار",
        "shared_summary_section": "الملخص المشترك",
        "share_with_students": "شارك مع الطلاب",
        "summary_shared_confirmation": "تم مشاركة الملخص مع الطلاب ✓",
        "num_questions_label": "عدد الأسئلة: %d",
        "quiz_duration_label": "مدة الاختبار: %d د",
        "invite_friends": "ادع أصدقاء",
        "share_room_invite_text": "انضم لغرفتي بذكّي! الكود: %@",
        "room_code_label": "كود الغرفة: %@",
        "participants_title": "المشاركين",
        "participants_section": "المشاركين",
        "raised_hands_section": "رافعين إيدهم",
        "raised_hands_count": "%d رافعين إيدهم",
        "raise_hand": "ارفع إيدك",
        "lower_hand": "أنزل إيدك",
        "start_class": "ابدأ الحصة",
        "waiting_for_teacher": "بانتظار المعلم يبدأ الحصة",
        "chat_message_placeholder": "اكتب رسالة...",
        "grant_write_access": "منح صلاحية الكتابة على السبورة",
        "revoke_write_access": "سحب صلاحية الكتابة",
        "grant_content_access": "منح صلاحية الرفع والاختبار",
        "revoke_content_access": "سحب الصلاحية",
        "force_mute": "كتم إجباري",
        "kick": "طرد",
        "kicked_alert": "تم طردك من الغرفة",
        "err_invite_failed": "تعذر إرسال الدعوة",
        "invite_sent": "تم الإرسال ✓",
        "btn_invite_friend": "📨 ادعُ صديق",
        "invite_friend_no_friends": "ما ضفت أصدقاء بعد",
        "top_results_heading": "🏆 نتائج الاختبار",
        "status_still_solving": "لسا يحل...",
        "host_badge": "👑 المضيف",
        "permission_granted_badge": "عنده صلاحية",
        "storekit_unavailable": "المنتجات غير متاحة الآن (تحتاج تشغيل من Xcode مباشرة أو حساب App Store Connect مفعّل)",
        "plan_free": "مجاني",
        "plan_plus": "بلس",
        "plan_pro": "برو",
        "plan_ultimate": "ألتميت",
        "plan_owner": "مالك التطبيق",
        "plan_plus_description": "٢٠ كتاب مكتبة، ٥ جلسات فردية يوميًا، ٣ جلسات جماعية يوميًا، درس مباشر واحد يوميًا، آخر ١٥ جلسة أرشيف، آخر ٨ اختبار أداء",
        "plan_pro_description": "٣٠ كتاب مكتبة، ١٠ جلسات فردية يوميًا، ٥ جلسات جماعية يوميًا، ٣ دروس مباشرة يوميًا، آخر ٣٠ جلسة أرشيف، آخر ١٥ اختبار أداء",
        "plan_ultimate_description": "٥٠ كتاب مكتبة، جلسات فردية وجماعية بلا حدود، ٨ دروس مباشرة يوميًا، أرشيف وأداء كامل",
        "subscribe_button": "اشترك",
        "monthly_label": "شهري",
        "yearly_label": "سنوي",
        "performance_guest_gate": "سجل دخول عشان تشوف أداءك",
        "streak_label": "أيام متتالية",
        "study_hours_label": "ساعات مذاكرة",
        "longest_streak_label": "أطول سلسلة",
        "score_progress_title": "تطور الدرجات",
        "weak_topics_title": "نقاط تحتاج مراجعة",
        "attempt_axis": "المحاولة",
        "percentage_axis": "النسبة",
        "add_friend": "إضافة صديق",
        "ask_a_question": "اسأل سؤال...",
        "average_score": "متوسط الدرجات",
        "bio": "نبذة عنك",
        "bio_placeholder": "اكتب نبذة بسيطة عنك...",
        "chat": "المحادثة",
        "chat_with_ai": "اسأل ذكّي",
        "chat_with_ai_subtitle": "اسأل عن أي شي بالملف",
        "close": "إغلاق",
        "co_host_badge": "مساعد",
        "confirm_kick": "متأكد تبي تطرد هذا المشارك؟",
        "connecting_to_room": "يتصل بالغرفة...",
        "current_streak": "أيام متتالية",
        "date": "التاريخ",
        "decline": "رفض",
        "duration_minutes_format": "المدة: %d دقيقة",
        "friend_request_sent": "تم إرسال طلب الصداقة ✓",
        "friend_requests": "طلبات الصداقة",
        "friends_count": "عدد الأصدقاء",
        "generate_quiz": "توليد اختبار",
        "generate_quiz_subtitle": "اختبر نفسك بأسئلة من الملف",
        "generating_quiz": "يولّد الاختبار...",
        "grant_permission": "منح صلاحية",
        "invalid_qr_code": "رمز QR غير صالح",
        "invite": "دعوة",
        "invite_from": "دعوة من %@",
        "invite_to_room": "دعوة للغرفة",
        "invited": "تمت الدعوة",
        "join": "انضمام",
        "join_by_code": "انضم بالكود",
        "join_voice": "انضم للصوت",
        "kicked_from_room": "تم طردك",
        "kicked_from_room_desc": "قام المضيف بطردك من هذه الغرفة",
        "leaderboard": "لوحة النتائج",
        "leave_voice": "غادر الصوت",
        "longest_streak": "أطول سلسلة",
        "mute": "كتم",
        "next_question": "السؤال التالي",
        "no_friends_yet": "ما عندك أصدقاء بعد",
        "num_questions_format": "عدد الأسئلة: %d",
        "participants": "المشاركين",
        "participants_count": "المشاركون (%d)",
        "paste_text_here": "الصق النص هنا...",
        "performance_empty": "ما فيه بيانات أداء بعد",
        "prepare_quiz": "تجهيز الاختبار",
        "privacy_settings": "إعدادات الخصوصية",
        "private_profile": "بروفايل خاص",
        "progress_over_time": "التطور عبر الوقت",
        "qr_scan_hint": "خلي صديقك يمسح هذا الرمز عشان يضيفك",
        "question_number": "السؤال %d من %d",
        "quiz_settings": "إعدادات الاختبار",
        "revoke_permission": "سحب الصلاحية",
        "room_code_placeholder": "أدخل كود الغرفة",
        "room_management": "إدارة الغرفة",
        "scan_qr_code": "امسح رمز QR",
        "score_percent": "النسبة %",
        "search_by_username": "ابحث باسم المستخدم",
        "search_results": "نتائج البحث",
        "session_hosted_by": "استضافة %@",
        "session_invites": "دعوات الجلسات",
        "share_room_code": "شارك كود الغرفة",
        "shared_summary": "الملخص المشترك",
        "show_archive_on_profile": "إظهار الأرشيف بالبروفايل",
        "show_friends_on_profile": "إظهار الأصدقاء بالبروفايل",
        "show_library_on_profile": "إظهار المكتبة بالبروفايل",
        "show_performance_on_profile": "إظهار الأداء بالبروفايل",
        "source_text": "نص المذاكرة",
        "start_quiz": "ابدأ الاختبار",
        "study": "المذاكرة",
        "total_attempts": "عدد المحاولات",
        "type_a_message": "اكتب رسالة...",
        "waiting_for_host": "بانتظار المضيف",
        "weak_topics": "نقاط تحتاج مراجعة",
        "your_score_format": "درجتك: %d من %d",
        "camera_permission_denied": "لازم تسمح باستخدام الكاميرا عشان تمسح رمز QR",
        "camera_unavailable": "الكاميرا غير متوفرة على هذا الجهاز",
        "open_settings": "افتح الإعدادات",
        "extracted_text": "نص الملف",
        "show_more": "عرض المزيد",
        "show_less": "عرض أقل",
        "chat_empty_title": "اسأل عن أي شي بالملف",
        "chat_empty_subtitle": "مثلًا: لخّص لي الفكرة الرئيسية، أو وضّح لي هذي النقطة",
        "is_typing": "%@ يكتب...",
        "are_typing": "أكثر من شخص يكتبون...",
        "add_text_to_board": "أضف نص للسبورة",
        "chat_closed": "المدرس قفل الشات مؤقتًا",
        "choose_file": "اختر ملف",
        "close_chat": "قفل الشات",
        "generate_summary": "ولّد الملخص",
        "open_chat": "فتح الشات",
        "share_summary_with_room": "شارك الملخص مع الطلاب",
        "start_solo_study": "ابدأ مذاكرة فردية",
        "start_solo_study_subtitle": "ملخص واختبار ودردشة ذكية",
        "summary_required_hint": "لازم تولّد الملخص قبل ما تقدر تبدأ الاختبار",
        "text_placeholder": "النص",
        "billing_period": "الفترة",
        "current_plan_badge": "باقتك الحالية",
        "restore_purchases": "استعادة المشتريات",
        "return_to_room": "الرجوع للغرفة",

        // ---- نظام إدارة حسابات المدارس (٥ أدوار) ----
        "email_or_username": "الإيميل أو اسم المستخدم",
        "err_wrong_credentials": "الإيميل/اسم المستخدم أو كلمة المرور غلط",
        "force_pw_heading": "لازم تغيّر كلمة السر أول",
        "force_pw_desc": "حسابك اتسوى بكلمة سر مؤقتة - اختر كلمة سر جديدة تعرفها بس قبل ما تكمل",
        "confirm_password": "أعد كتابتها",
        "err_password_min": "كلمة السر لازم ٦ أحرف على الأقل",
        "err_password_mismatch": "كلمتا السر ما تتطابقان",
        "my_schedule": "جدولي",
        "messages": "الرسائل",

        "admin_dash_label": "🛠️ لوحة الإدارة العامة",
        "admin_dash_heading": "المدارس المشتركة",
        "admin_add_school_heading": "➕ إضافة مدرسة جديدة",
        "ph_school_name": "اسم المدرسة",
        "ph_school_admin_email": "إيميل مدير المدرسة",
        "ph_max_accounts": "الحد الأقصى للحسابات",
        "btn_create_school": "إنشاء المدرسة",
        "admin_schools_list_heading": "🏫 كل المدارس",
        "th_school_name": "المدرسة",
        "th_admin_email": "إيميل المدير",
        "th_accounts_usage": "الحسابات",
        "th_status": "الحالة",
        "th_actions": "إجراء",
        "status_active": "مفعّلة",
        "status_inactive": "موقوفة",
        "btn_activate": "تفعيل",
        "btn_deactivate": "إيقاف",
        "btn_reset_password": "🔑 كلمة سر جديدة",
        "confirm_reset_school_password": "بيتولّد كلمة سر جديدة لمدير هذي المدرسة وتلغي القديمة - متأكد؟",
        "admin_password_reset_msg": "✅ كلمة سر جديدة (تظهر مرة وحدة بس، احفظها الحين)",
        "admin_no_schools": "ما فيه مدارس بعد",
        "confirm_delete_school": "بيتحذف كل شي يخص هذي المدرسة نهائيًا (المعلمين والطلاب والفصول والحضور) - ما يرجع بعدها. متأكد؟",

        "school_dash_label": "🏫 لوحة إدارة المدرسة",
        "school_dash_heading": "إدارة المدرسة",
        "school_usage_text": "الحسابات المستخدمة: %d من %d",
        "tab_teachers": "👨‍🏫 المعلمون",
        "tab_students": "👥 الطلاب",
        "tab_classes": "🏷️ الفصول والجدول",
        "tab_bulk_students": "➕ إضافة طلاب",
        "tab_attendance": "📋 الحضور",
        "tab_library": "📚 المكتبة",
        "ph_teacher_name": "اسم المعلم",
        "ph_teacher_email": "إيميل المعلم",
        "btn_add_teacher": "إضافة معلم",
        "school_no_teachers": "ما فيه معلمين مضافين بعد",
        "school_teacher_created_msg": "✅ تم إضافة المعلم - بيانات دخوله (تظهر مرة وحدة بس)",
        "admin_staff_heading": "🧑‍💼 إداريو المدرسة",
        "ph_admin_staff_name": "اسم الإداري",
        "ph_admin_staff_email": "إيميل الإداري",
        "btn_add_admin_staff": "إضافة إداري",
        "school_no_admin_staff": "ما فيه إداريين مضافين بعد",
        "school_admin_staff_created_msg": "✅ تم إضافة الإداري - بيانات دخوله (تظهر مرة وحدة بس)",
        "no_students_in_school": "ما فيه طلاب مضافين بعد",
        "th_full_name": "الاسم الكامل",
        "confirm_reset_account_password": "بيتولّد كلمة سر جديدة لهذا الحساب وتلغي القديمة - متأكد؟",
        "reset_password_result_msg": "✅ كلمة سر جديدة (تظهر مرة وحدة بس، احفظها الحين)",
        "th_name": "الاسم",
        "th_classes": "الفصول",
        "th_student_count": "عدد الطلاب",
        "th_last_login": "آخر دخول",
        "never_logged_in": "ما دخل بعد",
        "ph_class_name": "اسم الفصل",
        "btn_add_class": "إضافة فصل",
        "school_no_classes": "ما فيه فصول مضافة بعد",
        "th_class_name": "الفصل",
        "th_teacher": "المعلم",
        "opt_no_teacher_yet": "— بدون معلم بعد —",
        "schedule_heading": "🗓️ جدول الحصص",
        "ph_subject": "المادة",
        "btn_add_schedule": "إضافة حصة",
        "th_day": "اليوم",
        "th_time": "الوقت",
        "th_subject": "المادة",
        "no_schedule_yet": "ما فيه حصص مضافة بعد",
        "bulk_add_desc": "اكتب اسم طالب بكل سطر - النظام يولّد اسم مستخدم وكلمة سر لكل واحد تلقائيًا",
        "ph_bulk_names": "سارة أحمد\nمحمد علي",
        "btn_bulk_add": "إضافة الطلاب",
        "bulk_result_heading": "✅ الحسابات المولّدة (احفظها الحين)",
        "th_username": "اسم المستخدم",
        "th_password": "كلمة السر",
        "btn_export_csv": "⬇️ تصدير / مشاركة",
        "opt_create_class_first": "أنشئ فصل أول",
        "opt_all_classes": "كل الفصول",
        "th_student": "الطالب",
        "th_join_time": "وقت الانضمام",
        "broadcast_teachers_heading": "📢 رسالة جماعية لكل معلمي المدرسة",
        "ph_broadcast_body": "اكتب رسالتك هنا...",
        "btn_send_broadcast": "إرسال للجميع",
        "err_broadcast_body_required": "لازم تكتب نص الرسالة",
        "broadcast_sent_msg": "✅ وصلت لـ %d حساب",
        "confirm_delete_class": "متأكد تبي تحذف هذا الفصل؟",
        "confirm_delete_account": "متأكد تبي تحذف هذا الحساب؟ ما يرجع بعدها",
        "btn_delete": "حذف",

        "teacher_dash_label": "👨‍🏫 لوحة المعلم",
        "teacher_dash_heading": "فصولي",
        "tab_roster": "👥 الطلاب",
        "tab_performance": "📊 الأداء",
        "tab_schedule": "🗓️ جدولي",
        "teacher_no_students": "ما فيه طلاب بهذا الفصل بعد",
        "btn_view_profile": "عرض البروفايل",
        "teacher_student_no_archive": "ما فيه جلسات مسجّلة بعد",
        "btn_start_live_class": "🖍️ ابدأ درس مباشر",
        "th_attempts": "المحاولات",
        "th_avg_score": "متوسط الدرجات",
        "th_study_minutes": "دقائق المذاكرة",
        "th_streak": "الستريك",
        "opt_all_my_classes": "كل فصولي",
        "err_pick_class_first": "اختر فصل أول",
        "broadcast_students_heading": "📢 رسالة جماعية لطلاب الفصل المختار",
        "manual_attendance_heading": "📋 تسجيل حضور اليوم",
        "auto_attendance_heading": "🔗 الحضور التلقائي",
        "attendance_status_present": "حاضر",
        "attendance_status_late": "متأخر",
        "attendance_status_absent": "غايب",
        "btn_save_attendance": "حفظ الحضور",
        "attendance_saved_msg": "✅ تم حفظ الحضور",

        "student_schedule_label": "🗓️ جدولي",
        "student_schedule_heading": "جدول حصصي",

        "messages_label": "💬 الرسائل",
        "messages_heading": "الرسائل والتنبيهات",
        "tab_conversations": "💬 المحادثات",
        "tab_notifications": "🔔 التنبيهات",
        "ph_search_username": "ابحث باسم مستخدم لبدء محادثة",
        "no_conversations_yet": "ما فيه محادثات بعد",
        "you_label": "أنت",
        "btn_message": "راسله",
        "no_users_found": "ما فيه نتائج",
        "no_notifications_yet": "ما فيه تنبيهات بعد",
        "btn_start_now": "🖍️ ابدأ الحصة الآن",
        "btn_join_class_now": "🖍️ انضم للحصة الآن",

        "day_0": "الأحد", "day_1": "الاثنين", "day_2": "الثلاثاء", "day_3": "الأربعاء",
        "day_4": "الخميس", "day_5": "الجمعة", "day_6": "السبت",
    ]

    static let en: [String: String] = [
        "app_name": "zakiy",
        "welcome_title": "Welcome to zakiy",
        "welcome_subtitle": "AI-assisted collaborative study platform",
        "login": "Login",
        "signup": "Sign Up",
        "continue_guest": "Continue as Guest",
        "email": "Email",
        "password": "Password",
        "username": "Name",
        "education_level": "Education Level",
        "proficiency_level": "Proficiency",
        "already_have_account": "Have an account?",
        "no_account": "No account?",
        "home": "Home",
        "rooms": "Rooms",
        "library": "Library",
        "performance": "Performance",
        "settings": "Settings",
        "upload_pdf": "Upload PDF",
        "upload_pdf_subtitle": "Start a solo session from a new file",
        "solo_study": "Solo Study",
        "group_room": "Group Room",
        "group_room_subtitle": "Study with classmates in a live room",
        "live_lesson_subtitle": "Whiteboard and live group voice with your students",
        "room_type_classroom": "Live Lesson",
        "room_type_quiz": "Group Room",
        "summary": "Summary",
        "quiz": "Quiz",
        "chat_assistant": "Ask zakiy",
        "login_required_for_rooms": "You must log in to join a live lesson or group session",
        "create_room": "Create Room",
        "join_room": "I Have a Code",
        "room_code": "Room Code",
        "your_name": "Your Name",
        "logout": "Log Out",
        "language": "Language",
        "appearance": "Appearance",
        "appearance_system": "System",
        "appearance_light": "Light",
        "appearance_dark": "Dark",
        "subscription": "Subscription",
        "subscription_subtitle": "Manage your plan and subscription",
        "friends": "Friends",
        "friends_subtitle": "Add friends and view friend requests",
        "archive": "Archive",
        "archive_subtitle": "Past group study sessions",
        "notes": "My Notes",
        "notes_subtitle": "Your personal notebook",
        "notes_search_placeholder": "Search notes...",
        "notes_new": "New note",
        "notes_empty": "No notes here yet",
        "notes_folder_all": "All",
        "notes_folder_unfiled": "Unfiled",
        "notes_new_folder": "New folder",
        "notes_folder_name_placeholder": "Folder name",
        "notes_untitled": "Untitled",
        "notes_delete_confirm": "Delete this note permanently?",
        "notes_delete_folder_confirm": "Delete this folder? Notes inside it stay, just unfiled",
        "note_type_text": "Text",
        "note_type_checklist": "To-do",
        "note_title_placeholder": "Note title",
        "note_content_placeholder": "Write your note here...",
        "note_checklist_add_placeholder": "Add item...",
        "note_folder_label": "Folder",
        "note_pin": "Pin",
        "note_unpin": "Unpin",
        "ai_assistant": "AI Assistant",
        "ai_assistant_subtitle": "Chat with Zakiy or have it summarize a book",
        "ai_conversations_empty": "No conversations yet - start a new one!",
        "ai_new_conversation_title": "New conversation",
        "ai_empty_conversation": "Ask Zakiy anything, or summarize a book with the book button below",
        "ai_message_placeholder": "Type your message...",
        "ai_summarize_book": "Summarize a book",
        "ai_source_library": "From your library",
        "ai_source_upload": "Upload a file",
        "ai_upload_hint": "Upload a PDF and Zakiy will summarize it for you",
        "ai_pick_file": "Choose a PDF file",
        "assignments": "Assignments",
        "assignments_subtitle": "Your assignments and submissions",
        "assignments_heading": "Assignments",
        "assignment_new_heading": "New assignment",
        "assignment_class_label": "Class",
        "assignment_subject_placeholder": "Subject name",
        "assignment_title_placeholder": "Assignment title",
        "assignment_content_placeholder": "Assignment content",
        "btn_create_assignment": "Create assignment",
        "assignments_empty": "No assignments yet",
        "assignment_status_pending": "Not solved yet",
        "assignment_status_done": "Solved",
        "assignment_submitted_count": "%d/%d submitted",
        "assignment_submit_heading": "Solve assignment",
        "btn_pick_assignment_file": "Pick solution file",
        "assignment_note_placeholder": "Note (optional)",
        "btn_submit_assignment": "Submit assignment",
        "assignment_students_heading": "Submission status",
        "assignment_grade_label": "Grade",
        "btn_save_grade": "Save grade",
        "btn_view_file": "View file",
        "assignment_no_students": "No students in this class yet",
        "assignment_submitted_file_label": "Submitted file: %@",
        "assignment_note_shown": "Your note: %@",
        "assignment_grade_shown": "Grade: %@",
        "assignment_not_graded_yet": "Not graded yet",
        "err_assignment_need_class": "You need to pick a class",

        "quizzes": "Quizzes",
        "quizzes_subtitle": "Your class quizzes and grades",
        "quizzes_heading": "Quizzes",
        "quizzes_empty": "No quizzes yet",
        "quiz_new_heading": "New quiz",
        "quiz_edit_heading": "Edit quiz",
        "quiz_class_label": "Class",
        "quiz_subject_placeholder": "Subject name",
        "quiz_title_placeholder": "Quiz title",
        "quiz_time_limit_stepper_label": "Time limit: %d min",
        "quiz_time_limit_minutes_format": "%d min",
        "quiz_questions_heading": "Questions",
        "btn_add_question": "Add question",
        "quiz_question_type_label": "Question type",
        "quiz_type_mcq": "Multiple choice",
        "quiz_type_true_false": "True / False",
        "quiz_type_essay": "Essay",
        "quiz_question_text_placeholder": "Question text",
        "btn_add_choice": "Add choice",
        "quiz_choice_placeholder": "Choice %d",
        "quiz_mark_correct_hint": "Mark the correct answer (optional)",
        "quiz_true_label": "True",
        "quiz_false_label": "False",
        "btn_create_quiz": "Create quiz",
        "btn_save_changes": "Save changes",
        "err_quiz_need_class": "You need to pick a class",
        "err_quiz_need_question": "You need at least one question with text",
        "quiz_status_draft": "Draft",
        "quiz_status_published": "Published",
        "quiz_status_not_taken": "Not taken yet",
        "quiz_submitted_count": "%d/%d submitted",
        "btn_publish_quiz": "Publish quiz",
        "quiz_publish_confirm_title": "Publish quiz",
        "quiz_publish_confirm_message": "Once published you won't be able to edit or delete this quiz. Publish it?",
        "quiz_delete_confirm_title": "Delete quiz",
        "quiz_delete_confirm_message": "Are you sure you want to delete this quiz?",
        "quiz_students_heading": "Students status",
        "quiz_no_students": "No students in this class yet",
        "quiz_view_answers": "View answers",
        "quiz_hide_answers": "Hide answers",
        "quiz_correct_answer_label": "Correct answer: %@",
        "quiz_student_answer_label": "Student's answer: %@",
        "quiz_no_answer": "No answer",
        "quiz_auto_submitted_badge": "Auto-submitted (time ran out)",
        "quiz_time_remaining_label": "Time remaining: %@",
        "btn_submit_quiz": "Submit quiz",
        "quiz_submit_confirm_title": "Submit quiz",
        "quiz_submit_confirm_message": "Are you sure you want to submit your answers?",
        "quiz_result_graded_heading": "Your result",
        "quiz_result_grade_format": "Grade: %@",
        "quiz_awaiting_grade": "Awaiting grading",
        "quiz_result_awaiting_message": "Your answers were submitted, awaiting your teacher's grading",
        "quiz_result_auto_submitted_message": "Time ran out and your answers were submitted automatically",
        "quiz_essay_answer_placeholder": "Write your answer here",

        // ---- Madrasati: official site shortcut + Zakiy's own independent AI tools (any logged-in account) ----
        "nav_madrasati": "Madrasati",
        "madrasati_nav_subtitle": "Madrasati shortcut + Zakiy tools for teachers & students",
        "madrasati_heading": "Madrasati & Zakiy teacher tools",
        "madrasati_desc": "A quick shortcut to the official Madrasati site, plus Zakiy's own AI tools for teachers - fully independent of Madrasati, sharing no data with it whatsoever.",
        "madrasati_link_desc": "Opens the official Madrasati site in a new tab - you sign in there directly, and Zakiy never sees or touches your account data there.",
        "btn_open_madrasati": "🔗 Open official Madrasati",
        "teacher_tools_heading": "👨‍🏫 Zakiy tools for teachers",
        "btn_new_lesson_prep": "➕ New AI lesson preparation",
        "btn_open_enrichment": "🌟 Enrichment activity",
        "btn_open_results_analysis": "📊 Analyze student results",
        "saved_lesson_preps_heading": "📁 My saved preparations",
        "lesson_prep_empty": "No saved preparations yet.",
        "student_tools_heading": "🎒 Zakiy tools for students",
        "btn_new_homework_help": "➕ New homework helper",
        "btn_new_study_plan": "🗓️ New study plan",
        "saved_homework_help_heading": "📁 Saved homework helper sessions",
        "homework_help_empty": "No saved sessions yet.",
        "saved_study_plans_heading": "📁 Saved study plans",
        "study_plan_empty": "No saved plans yet.",

        "lesson_prep_create_heading": "New lesson preparation",
        "lesson_prep_view_heading": "Lesson preparation",
        "ph_lesson_prep_subject": "Subject",
        "ph_lesson_prep_grade": "Grade level",
        "ph_lesson_prep_unit": "Unit (optional)",
        "ph_lesson_prep_title": "Lesson title",
        "btn_generate_lesson_prep": "✨ Generate preparation",
        "err_lesson_prep_fields_required": "You need the subject, grade level, and lesson title",
        "err_lesson_prep_gen_failed": "Could not generate the preparation, try again",
        "lp_objectives_label": "🎯 Learning objectives",
        "lp_intro_label": "🚪 Introduction",
        "lp_steps_label": "📋 Lesson steps",
        "lp_activities_label": "🎲 Classroom activities",
        "lp_assessment_label": "📊 Assessment",
        "lp_homework_label": "📝 Homework",
        "lp_enrichment_label": "🌟 Enrichment",
        "btn_save_lesson_prep": "💾 Save preparation",
        "btn_copy_lesson_prep": "📋 Copy preparation",
        "btn_regenerate_lesson_prep": "🔄 Regenerate",
        "btn_delete_lesson_prep": "🗑️ Delete",
        "copied_label": "✅ Copied",
        "saved_label": "✅ Saved",
        "err_copy_failed": "Could not copy",
        "confirm_delete_lesson_prep": "Delete this preparation permanently?",

        "enrichment_heading": "Enrichment activity generator",
        "enrichment_desc": "Enter the subject, grade, and topic - Zakiy suggests a ready enrichment activity for advanced students.",
        "ph_topic": "Topic",
        "btn_generate_enrichment": "✨ Generate activity",

        "results_analysis_heading": "Student results analyzer",
        "results_analysis_desc": "Paste your students' scores/results in any format (names and grades), and Zakiy analyzes them to surface strengths, weaknesses, and students who need follow-up.",
        "ph_raw_results": "Example:\nAhmed: 18/20\nSara: 12/20",
        "btn_generate_results_analysis": "✨ Analyze results",
        "err_raw_results_required": "You need to paste the student results",
        "ra_summary_label": "📝 Overall summary",
        "ra_strengths_label": "💪 Strengths",
        "ra_weaknesses_label": "⚠️ Weaknesses",
        "ra_at_risk_label": "🚨 Need follow-up",
        "ra_recommendations_label": "✅ Recommendations",

        "homework_help_create_heading": "New homework helper",
        "homework_help_view_heading": "Homework helper",
        "ph_homework_topic": "Topic or homework question",
        "btn_generate_homework_help": "✨ Help me",
        "btn_save_homework_help": "💾 Save",
        "confirm_delete_homework_help": "Delete this homework helper session permanently?",
        "hh_explanation_label": "💡 Explanation",
        "hh_example_label": "📐 Worked example",
        "hh_practice_label": "✏️ Practice questions",
        "hh_tips_label": "💡 Tip",

        "study_plan_create_heading": "New study plan",
        "study_plan_view_heading": "Study plan",
        "ph_study_plan_subjects": "Subjects (comma-separated)",
        "ph_study_plan_hours": "Study hours per day (optional)",
        "study_plan_exam_date_toggle": "Add exam date",
        "study_plan_exam_date_label": "Exam date",
        "btn_generate_study_plan": "✨ Generate plan",
        "btn_save_study_plan": "💾 Save",
        "err_study_plan_subjects_required": "You need to enter the subjects you want to study",
        "confirm_delete_study_plan": "Delete this study plan permanently?",
        "sp_tips_label": "💡 General tips",

        "current_plan": "Current Plan",
        "free_plan": "Free",
        "greeting_prefix": "Hi, %@",
        "home_greeting_subtitle": "Ready to study today?",
        "default_student_name": "Student",
        "loading": "Loading...",
        "error_generic": "Something went wrong, try again",
        "err_unexpected_response": "Unexpected server response",
        "err_server_status": "Server error (%d)",
        "ok": "OK",
        "cancel": "Cancel",
        "save": "Save",
        "add": "Add",
        "search": "Search",
        "delete": "Delete",
        "rename": "Rename",
        "edit": "Edit",
        "next": "Next",
        "finish": "Finish",
        "library_guest_gate": "Log in to see your library",
        "library_empty": "No saved books yet",
        "library_pick_empty": "No books in your library yet - save one from a solo session first",
        "pick_from_library": "Choose from your library",
        "add_book": "Add Book",
        "upload_from_device": "Upload from your device",
        "rename_book_title": "Rename Book",
        "book_title_placeholder": "Book title",
        "confirm_delete_book": "Are you sure you want to delete this book from your library?",
        "save_to_library_title": "Save to Your Library",
        "library_count_label": "%d books in library",
        "open_for_study": "Open for Study",
        "archive_guest_gate": "Log in to see your archive",
        "archive_empty": "No group sessions or lessons in your archive yet",
        "archive_host_label": "Host: %@",
        "friends_guest_gate": "Log in to add friends",
        "friends_empty": "You don't have any friends yet",
        "my_friends": "My Friends",
        "friends_count_label": "%d friends",
        "add_friend_section": "Add a Friend",
        "search_username_placeholder": "Search by username",
        "incoming_requests": "Incoming Requests",
        "outgoing_requests": "Sent Requests",
        "pending_label": "Pending",
        "accept": "Accept",
        "reject": "Reject",
        "remove_friend": "Remove",
        "confirm_remove_friend": "Are you sure you want to remove this friend?",
        "my_qr_code": "Your QR Code",
        "scan_qr": "Scan QR Code",
        "join_room_qr": "Room Join Code",
        "session_invites_heading": "📩 Session Invites",
        "session_invites_empty": "No new invites",
        "invite_from_prefix": "Invite from %@",
        "btn_join_now": "Join Now",
        "btn_dismiss_invite": "Dismiss",
        "profile": "Profile",
        "my_profile": "My Profile",
        "my_profile_subtitle": "Bio, school, and data privacy",
        "private_profile_badge": "Private",
        "private_profile_notice": "This profile is private - only its owner can see its details",
        "already_friends_badge": "Already friends",
        "incoming_request_notice": "Sent you a friend request - accept it from the Friends screen",
        "add_friend_button": "Add Friend",
        "stat_attempts": "Attempts",
        "stat_avg_score": "Avg Score",
        "stat_study_minutes": "Study Minutes",
        "stat_streak": "Day Streak",
        "profile_bio_section": "About You",
        "profile_bio_placeholder": "Write a short bio about yourself...",
        "school_name_placeholder": "Your school name",
        "private_profile_toggle": "Make my whole profile private",
        "private_profile_footer": "If enabled, no one can see anything on your profile besides your name, even friends.",
        "profile_sections_visibility_heading": "Visible on public profile",
        "guest_mode_label": "Guest Mode",
        "not_logged_in_label": "Not logged in",
        "edit_profile": "Edit Profile",
        "edit_profile_subtitle": "Name, phone number, and password",
        "phone_number": "Phone Number",
        "new_password": "New Password",
        "update_password": "Update Password",
        "profile_updated": "Profile updated ✓",
        "password_updated": "Password updated ✓",
        "start_study_button": "Start Studying",
        "start_quiz_button": "Start Quiz",
        "start_quiz_final_button": "Start Quiz for Everyone",
        "step_pick_file_title": "Pick a File",
        "step_summary_title": "Summary",
        "step_quiz_title": "Quiz",
        "next_generate_quiz": "Next: Generate Quiz",
        "shared_summary_section": "Shared Summary",
        "share_with_students": "Share with Students",
        "summary_shared_confirmation": "Summary shared with students ✓",
        "num_questions_label": "Questions: %d",
        "quiz_duration_label": "Duration: %d min",
        "invite_friends": "Invite Friends",
        "share_room_invite_text": "Join my room on zakiy! Code: %@",
        "room_code_label": "Room Code: %@",
        "participants_title": "Participants",
        "participants_section": "Participants",
        "raised_hands_section": "Raised Hands",
        "raised_hands_count": "%d raised hands",
        "raise_hand": "Raise Hand",
        "lower_hand": "Lower Hand",
        "start_class": "Start Class",
        "waiting_for_teacher": "Waiting for the teacher to start",
        "chat_message_placeholder": "Type a message...",
        "grant_write_access": "Grant whiteboard write access",
        "revoke_write_access": "Revoke write access",
        "grant_content_access": "Grant upload & quiz access",
        "revoke_content_access": "Revoke access",
        "force_mute": "Force Mute",
        "kick": "Kick",
        "kicked_alert": "You were removed from the room",
        "err_invite_failed": "Couldn't send the invite",
        "invite_sent": "Sent ✓",
        "btn_invite_friend": "📨 Invite Friend",
        "invite_friend_no_friends": "You haven't added any friends yet",
        "top_results_heading": "🏆 Quiz Results",
        "status_still_solving": "Still solving...",
        "host_badge": "👑 Host",
        "permission_granted_badge": "Has permission",
        "storekit_unavailable": "Products aren't available yet (needs a direct Xcode Run, or an active App Store Connect account)",
        "plan_free": "Free",
        "plan_plus": "Plus",
        "plan_pro": "Pro",
        "plan_ultimate": "Ultimate",
        "plan_owner": "App Owner",
        "plan_plus_description": "20 library books, 5 daily solo sessions, 3 daily group sessions, 1 daily live lesson, last 15 archived sessions, last 8 performance results",
        "plan_pro_description": "30 library books, 10 daily solo sessions, 5 daily group sessions, 3 daily live lessons, last 30 archived sessions, last 15 performance results",
        "plan_ultimate_description": "50 library books, unlimited solo & group sessions, 8 daily live lessons, full archive & performance history",
        "subscribe_button": "Subscribe",
        "monthly_label": "Monthly",
        "yearly_label": "Yearly",
        "performance_guest_gate": "Log in to see your performance",
        "streak_label": "Day Streak",
        "study_hours_label": "Study Hours",
        "longest_streak_label": "Longest Streak",
        "score_progress_title": "Score Progress",
        "weak_topics_title": "Needs Review",
        "attempt_axis": "Attempt",
        "percentage_axis": "Percentage",
        "add_friend": "Add Friend",
        "ask_a_question": "Ask a question...",
        "average_score": "Average Score",
        "bio": "Bio",
        "bio_placeholder": "Write a short bio about yourself...",
        "chat": "Chat",
        "chat_with_ai": "Ask zakiy",
        "chat_with_ai_subtitle": "Ask anything about the file",
        "close": "Close",
        "co_host_badge": "Co-Host",
        "confirm_kick": "Are you sure you want to kick this participant?",
        "connecting_to_room": "Connecting to room...",
        "current_streak": "Current Streak",
        "date": "Date",
        "decline": "Decline",
        "duration_minutes_format": "Duration: %d min",
        "friend_request_sent": "Friend request sent ✓",
        "friend_requests": "Friend Requests",
        "friends_count": "Friends",
        "generate_quiz": "Generate Quiz",
        "generate_quiz_subtitle": "Test yourself with questions from the file",
        "generating_quiz": "Generating quiz...",
        "grant_permission": "Grant Permission",
        "invalid_qr_code": "Invalid QR code",
        "invite": "Invite",
        "invite_from": "Invite from %@",
        "invite_to_room": "Invite to Room",
        "invited": "Invited",
        "join": "Join",
        "join_by_code": "Join by Code",
        "join_voice": "Join Voice",
        "kicked_from_room": "You Were Removed",
        "kicked_from_room_desc": "The host removed you from this room",
        "leaderboard": "Leaderboard",
        "leave_voice": "Leave Voice",
        "longest_streak": "Longest Streak",
        "mute": "Mute",
        "next_question": "Next Question",
        "no_friends_yet": "You don't have any friends yet",
        "num_questions_format": "Questions: %d",
        "participants": "Participants",
        "participants_count": "Participants (%d)",
        "paste_text_here": "Paste text here...",
        "performance_empty": "No performance data yet",
        "prepare_quiz": "Prepare Quiz",
        "privacy_settings": "Privacy Settings",
        "private_profile": "Private Profile",
        "progress_over_time": "Progress Over Time",
        "qr_scan_hint": "Have your friend scan this code to add you",
        "question_number": "Question %d of %d",
        "quiz_settings": "Quiz Settings",
        "revoke_permission": "Revoke Permission",
        "room_code_placeholder": "Enter room code",
        "room_management": "Room Management",
        "scan_qr_code": "Scan QR Code",
        "score_percent": "Score %",
        "search_by_username": "Search by username",
        "search_results": "Search Results",
        "session_hosted_by": "Hosted by %@",
        "session_invites": "Session Invites",
        "share_room_code": "Share Room Code",
        "shared_summary": "Shared Summary",
        "show_archive_on_profile": "Show archive on profile",
        "show_friends_on_profile": "Show friends on profile",
        "show_library_on_profile": "Show library on profile",
        "show_performance_on_profile": "Show performance on profile",
        "source_text": "Study Text",
        "start_quiz": "Start Quiz",
        "study": "Study",
        "total_attempts": "Total Attempts",
        "type_a_message": "Type a message...",
        "waiting_for_host": "Waiting for host",
        "weak_topics": "Needs Review",
        "your_score_format": "Your score: %d/%d",
        "camera_permission_denied": "Camera access is needed to scan a QR code",
        "camera_unavailable": "Camera isn't available on this device",
        "open_settings": "Open Settings",
        "extracted_text": "File Text",
        "show_more": "Show More",
        "show_less": "Show Less",
        "chat_empty_title": "Ask anything about the file",
        "chat_empty_subtitle": "For example: summarize the main idea, or explain this point",
        "is_typing": "%@ is typing...",
        "are_typing": "Several people are typing...",
        "add_text_to_board": "Add text to the board",
        "chat_closed": "The teacher paused the chat",
        "choose_file": "Choose a File",
        "close_chat": "Close Chat",
        "generate_summary": "Generate Summary",
        "open_chat": "Open Chat",
        "share_summary_with_room": "Share summary with students",
        "start_solo_study": "Start Solo Study",
        "start_solo_study_subtitle": "Summary, quiz, and AI chat",
        "summary_required_hint": "You need to generate the summary before you can start the quiz",
        "text_placeholder": "Text",
        "billing_period": "Period",
        "current_plan_badge": "Your Current Plan",
        "restore_purchases": "Restore Purchases",
        "return_to_room": "Return to Room",

        // ---- Multi-school account system (5 roles) ----
        "email_or_username": "Email or username",
        "err_wrong_credentials": "Wrong email/username or password",
        "force_pw_heading": "You need to change your password first",
        "force_pw_desc": "Your account was created with a temporary password - choose a new one only you know before continuing",
        "confirm_password": "Confirm password",
        "err_password_min": "Password must be at least 6 characters",
        "err_password_mismatch": "Passwords don't match",
        "my_schedule": "My Schedule",
        "messages": "Messages",

        "admin_dash_label": "🛠️ Platform Admin",
        "admin_dash_heading": "Subscribed Schools",
        "admin_add_school_heading": "➕ Add a New School",
        "ph_school_name": "School name",
        "ph_school_admin_email": "School admin's email",
        "ph_max_accounts": "Max accounts",
        "btn_create_school": "Create School",
        "admin_schools_list_heading": "🏫 All Schools",
        "th_school_name": "School",
        "th_admin_email": "Admin's Email",
        "th_accounts_usage": "Accounts",
        "th_status": "Status",
        "th_actions": "Action",
        "status_active": "Active",
        "status_inactive": "Inactive",
        "btn_activate": "Activate",
        "btn_deactivate": "Deactivate",
        "btn_reset_password": "🔑 New Password",
        "confirm_reset_school_password": "This generates a new password for this school's admin and invalidates the old one - continue?",
        "admin_password_reset_msg": "✅ New password (shown once, save it now)",
        "admin_no_schools": "No schools yet",
        "confirm_delete_school": "This permanently deletes everything for this school (teachers, students, classes, attendance) - this can't be undone. Continue?",

        "school_dash_label": "🏫 School Dashboard",
        "school_dash_heading": "Manage School",
        "school_usage_text": "Accounts used: %d of %d",
        "tab_teachers": "👨‍🏫 Teachers",
        "tab_students": "👥 Students",
        "tab_classes": "🏷️ Classes & Schedule",
        "tab_bulk_students": "➕ Add Students",
        "tab_attendance": "📋 Attendance",
        "tab_library": "📚 Library",
        "ph_teacher_name": "Teacher's name",
        "ph_teacher_email": "Teacher's email",
        "btn_add_teacher": "Add Teacher",
        "school_no_teachers": "No teachers added yet",
        "school_teacher_created_msg": "✅ Teacher added - their login (shown once)",
        "admin_staff_heading": "🧑‍💼 School Administrative Staff",
        "ph_admin_staff_name": "Staff member's name",
        "ph_admin_staff_email": "Staff member's email",
        "btn_add_admin_staff": "Add Staff Member",
        "school_no_admin_staff": "No administrative staff added yet",
        "school_admin_staff_created_msg": "✅ Staff member added - their login (shown once)",
        "no_students_in_school": "No students added yet",
        "th_full_name": "Full Name",
        "confirm_reset_account_password": "This generates a new password for this account and invalidates the old one - continue?",
        "reset_password_result_msg": "✅ New password (shown once, save it now)",
        "th_name": "Name",
        "th_classes": "Classes",
        "th_student_count": "Students",
        "th_last_login": "Last login",
        "never_logged_in": "Never logged in",
        "ph_class_name": "Class name",
        "btn_add_class": "Add Class",
        "school_no_classes": "No classes added yet",
        "th_class_name": "Class",
        "th_teacher": "Teacher",
        "opt_no_teacher_yet": "— No teacher yet —",
        "schedule_heading": "🗓️ Class Schedule",
        "ph_subject": "Subject",
        "btn_add_schedule": "Add Session",
        "th_day": "Day",
        "th_time": "Time",
        "th_subject": "Subject",
        "no_schedule_yet": "No classes scheduled yet",
        "bulk_add_desc": "Write one student name per line - the system auto-generates a username and password for each",
        "ph_bulk_names": "Sara Ahmed\nMohammed Ali",
        "btn_bulk_add": "Add Students",
        "bulk_result_heading": "✅ Generated Accounts (save now)",
        "th_username": "Username",
        "th_password": "Password",
        "btn_export_csv": "⬇️ Export / Share",
        "opt_create_class_first": "Create a class first",
        "opt_all_classes": "All classes",
        "th_student": "Student",
        "th_join_time": "Joined at",
        "broadcast_teachers_heading": "📢 Broadcast to All School Teachers",
        "ph_broadcast_body": "Write your message here...",
        "btn_send_broadcast": "Send to All",
        "err_broadcast_body_required": "Message text is required",
        "broadcast_sent_msg": "✅ Sent to %d account(s)",
        "confirm_delete_class": "Delete this class?",
        "confirm_delete_account": "Delete this account? This can't be undone",
        "btn_delete": "Delete",

        "teacher_dash_label": "👨‍🏫 Teacher Dashboard",
        "teacher_dash_heading": "My Classes",
        "tab_roster": "👥 Students",
        "tab_performance": "📊 Performance",
        "tab_schedule": "🗓️ My Schedule",
        "teacher_no_students": "No students in this class yet",
        "btn_view_profile": "View Profile",
        "teacher_student_no_archive": "No recorded sessions yet",
        "btn_start_live_class": "🖍️ Start a Live Lesson",
        "th_attempts": "Attempts",
        "th_avg_score": "Avg. Score",
        "th_study_minutes": "Study Minutes",
        "th_streak": "Streak",
        "opt_all_my_classes": "All my classes",
        "err_pick_class_first": "Pick a class first",
        "broadcast_students_heading": "📢 Broadcast to the Selected Class",
        "manual_attendance_heading": "📋 Take Today's Attendance",
        "auto_attendance_heading": "🔗 Automatic Attendance",
        "attendance_status_present": "Present",
        "attendance_status_late": "Late",
        "attendance_status_absent": "Absent",
        "btn_save_attendance": "Save Attendance",
        "attendance_saved_msg": "✅ Attendance saved",

        "student_schedule_label": "🗓️ My Schedule",
        "student_schedule_heading": "My Class Schedule",

        "messages_label": "💬 Messages",
        "messages_heading": "Messages & Notifications",
        "tab_conversations": "💬 Conversations",
        "tab_notifications": "🔔 Notifications",
        "ph_search_username": "Search by username to start a conversation",
        "no_conversations_yet": "No conversations yet",
        "you_label": "You",
        "btn_message": "Message",
        "no_users_found": "No results",
        "no_notifications_yet": "No notifications yet",
        "btn_start_now": "🖍️ Start the Class Now",
        "btn_join_class_now": "🖍️ Join the Class Now",

        "day_0": "Sunday", "day_1": "Monday", "day_2": "Tuesday", "day_3": "Wednesday",
        "day_4": "Thursday", "day_5": "Friday", "day_6": "Saturday",
    ]
}
