import Foundation

enum Loc {
    static func t(_ key: String) -> String {
        let lang = AppSettings.currentLanguageCode
        return (lang == "ar" ? ar[key] : en[key]) ?? key
    }

    static func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), arguments: args)
    }

    static let ar: [String: String] = [
        "app_name": "ذكّي",
        "welcome_title": "أهلًا بك في ذكّي",
        "welcome_subtitle": "منصة مذاكرة جماعية بمساعدة الذكاء الاصطناعي",
        "login": "تسجيل الدخول",
        "signup": "إنشاء حساب",
        "continue_guest": "استمر بدون حساب",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "username": "الاسم",
        "education_level": "المرحلة الدراسية",
        "proficiency_level": "المستوى",
        "already_have_account": "عندك حساب؟",
        "no_account": "ما عندك حساب؟",
        "home": "الرئيسية",
        "rooms": "الغرف",
        "library": "المكتبة",
        "performance": "أدائي",
        "settings": "الإعدادات",
        "upload_pdf": "ارفع ملف PDF",
        "upload_pdf_subtitle": "ابدأ مذاكرة فردية من ملف جديد",
        "solo_study": "مذاكرة فردية",
        "group_room": "غرفة جماعية",
        "group_room_subtitle": "ادرس مع زملائك بغرفة مباشرة",
        "live_lesson_subtitle": "سبورة وصوت جماعي حي مع طلابك",
        "room_type_classroom": "درس مباشر",
        "room_type_quiz": "غرفة جماعية",
        "summary": "الملخص",
        "quiz": "الاختبار",
        "chat_assistant": "اسأل ذكّي",
        "create_room": "أنشئ غرفة",
        "join_room": "عندي كود",
        "room_code": "كود الغرفة",
        "your_name": "اسمك",
        "logout": "تسجيل خروج",
        "language": "اللغة",
        "appearance": "المظهر",
        "appearance_system": "تلقائي",
        "appearance_light": "فاتح",
        "appearance_dark": "داكن",
        "subscription": "الاشتراك",
        "subscription_subtitle": "إدارة باقتك واشتراكك",
        "friends": "الأصدقاء",
        "friends_subtitle": "أضف أصدقاء وشوف طلبات الصداقة",
        "archive": "الأرشيف",
        "archive_subtitle": "جلسات المذاكرة الجماعية السابقة",
        "current_plan": "باقتك الحالية",
        "free_plan": "مجاني",
        "greeting_prefix": "أهلًا، %@",
        "home_greeting_subtitle": "جاهز تذاكر اليوم؟",
        "default_student_name": "طالب",
        "loading": "يحمّل...",
        "error_generic": "صار خطأ، جرب مرة ثانية",
        "err_unexpected_response": "رد غير متوقع من الخادم",
        "err_server_status": "خطأ من الخادم (%d)",
        "ok": "حسنًا",
        "cancel": "إلغاء",
        "save": "حفظ",
        "add": "إضافة",
        "search": "بحث",
        "delete": "حذف",
        "rename": "إعادة تسمية",
        "edit": "تعديل",
        "next": "التالي",
        "finish": "إنهاء",
        "library_guest_gate": "سجل دخول عشان تشوف مكتبتك",
        "library_empty": "ما فيه كتب محفوظة بعد",
        "library_pick_empty": "ما فيه كتب بمكتبتك بعد - احفظ ملف من المذاكرة الفردية أول",
        "pick_from_library": "اختر من مكتبتك",
        "add_book": "أضف كتاب",
        "upload_from_device": "ارفع من جهازك",
        "rename_book_title": "إعادة تسمية الكتاب",
        "book_title_placeholder": "اسم الكتاب",
        "confirm_delete_book": "متأكد تبي تحذف هذا الكتاب من مكتبتك؟",
        "save_to_library_title": "احفظ بمكتبتك",
        "library_count_label": "%d كتاب بالمكتبة",
        "open_for_study": "افتح للمذاكرة",
        "archive_guest_gate": "سجل دخول عشان تشوف أرشيفك",
        "archive_empty": "ما فيه جلسات جماعية أو دروس بأرشيفك لحد الحين",
        "archive_host_label": "المضيف: %@",
        "friends_guest_gate": "سجل دخول عشان تضيف أصدقاء",
        "friends_empty": "ما عندك أصدقاء بعد",
        "my_friends": "أصدقائي",
        "friends_count_label": "%d صديق",
        "add_friend_section": "إضافة صديق",
        "search_username_placeholder": "ابحث باسم المستخدم",
        "incoming_requests": "طلبات واردة",
        "outgoing_requests": "طلبات مرسلة",
        "pending_label": "قيد الانتظار",
        "accept": "قبول",
        "reject": "رفض",
        "remove_friend": "حذف",
        "confirm_remove_friend": "متأكد تبي تحذف هذا الصديق؟",
        "my_qr_code": "رمز QR الخاص فيك",
        "scan_qr": "امسح رمز QR",
        "join_room_qr": "رمز دخول الغرفة",
        "session_invites_heading": "📩 دعوات جلسات",
        "session_invites_empty": "ما فيه دعوات جديدة",
        "invite_from_prefix": "دعوة من %@",
        "btn_join_now": "انضم الآن",
        "btn_dismiss_invite": "تجاهل",
        "profile": "البروفايل",
        "my_profile": "بروفايلي",
        "my_profile_subtitle": "نبذة، مدرستك، وخصوصية بياناتك",
        "private_profile_badge": "خاص",
        "private_profile_notice": "هذا البروفايل خاص - ما يقدر يشوف تفاصيله غير صاحبه",
        "already_friends_badge": "صديقك بالفعل",
        "incoming_request_notice": "أرسل لك طلب صداقة - تقدر تقبله من شاشة الأصدقاء",
        "add_friend_button": "أضف صديق",
        "stat_attempts": "محاولات",
        "stat_avg_score": "متوسط الدرجات",
        "stat_study_minutes": "دقائق مذاكرة",
        "stat_streak": "أيام متتالية",
        "profile_bio_section": "نبذة عنك",
        "profile_bio_placeholder": "اكتب نبذة بسيطة عنك...",
        "school_name_placeholder": "اسم مدرستك",
        "private_profile_toggle": "خلي بروفايلي خاص بالكامل",
        "private_profile_footer": "لو فعّلته، محد يقدر يشوف أي شي بروفايلك غير اسمك، حتى لو كان صديقك.",
        "profile_sections_visibility_heading": "يظهر بالبروفايل العام",
        "guest_mode_label": "وضع الضيف",
        "not_logged_in_label": "ما سجلت دخول",
        "edit_profile": "تعديل البيانات",
        "edit_profile_subtitle": "الاسم، رقم الجوال، وكلمة المرور",
        "phone_number": "رقم الجوال",
        "new_password": "كلمة المرور الجديدة",
        "update_password": "تحديث كلمة المرور",
        "profile_updated": "تم تحديث البيانات ✓",
        "password_updated": "تم تحديث كلمة المرور ✓",
        "start_study_button": "ابدأ مذاكرة",
        "start_quiz_button": "ابدأ اختبار",
        "start_quiz_final_button": "ابدأ الاختبار للجميع",
        "step_pick_file_title": "اختيار ملف",
        "step_summary_title": "الملخص",
        "step_quiz_title": "الاختبار",
        "next_generate_quiz": "التالي: توليد الاختبار",
        "shared_summary_section": "الملخص المشترك",
        "share_with_students": "شارك مع الطلاب",
        "summary_shared_confirmation": "تم مشاركة الملخص مع الطلاب ✓",
        "num_questions_label": "عدد الأسئلة: %d",
        "quiz_duration_label": "مدة الاختبار: %d د",
        "invite_friends": "ادع أصدقاء",
        "share_room_invite_text": "انضم لغرفتي بذكّي! الكود: %@",
        "room_code_label": "كود الغرفة: %@",
        "participants_title": "المشاركين",
        "participants_section": "المشاركين",
        "raised_hands_section": "رافعين إيدهم",
        "raised_hands_count": "%d رافعين إيدهم",
        "raise_hand": "ارفع إيدك",
        "lower_hand": "أنزل إيدك",
        "start_class": "ابدأ الحصة",
        "waiting_for_teacher": "بانتظار المعلم يبدأ الحصة",
        "chat_message_placeholder": "اكتب رسالة...",
        "grant_write_access": "منح صلاحية الكتابة على السبورة",
        "revoke_write_access": "سحب صلاحية الكتابة",
        "grant_content_access": "منح صلاحية الرفع والاختبار",
        "revoke_content_access": "سحب الصلاحية",
        "force_mute": "كتم إجباري",
        "kick": "طرد",
        "kicked_alert": "تم طردك من الغرفة",
        "err_invite_failed": "تعذر إرسال الدعوة",
        "invite_sent": "تم الإرسال ✓",
        "btn_invite_friend": "📨 ادعُ صديق",
        "invite_friend_no_friends": "ما ضفت أصدقاء بعد",
        "top_results_heading": "🏆 نتائج الاختبار",
        "status_still_solving": "لسا يحل...",
        "host_badge": "👑 المضيف",
        "permission_granted_badge": "عنده صلاحية",
        "storekit_unavailable": "المنتجات غير متاحة الآن (تحتاج تشغيل من Xcode مباشرة أو حساب App Store Connect مفعّل)",
        "plan_free": "مجاني",
        "plan_plus": "بلس",
        "plan_pro": "برو",
        "plan_ultimate": "ألتميت",
        "plan_owner": "مالك التطبيق",
        "plan_plus_description": "٨ كتب مكتبة، ٥ جلسات يوميًا، ٣ غرف جماعية، درس مباشر واحد يوميًا",
        "plan_pro_description": "١٥ كتاب مكتبة، ١٠ جلسات يوميًا، ٥ غرف جماعية، ٥ دروس مباشرة يوميًا",
        "plan_ultimate_description": "٣٠ كتاب مكتبة، جلسات وغرف بلا حدود، ٨ دروس مباشرة يوميًا، أرشيف وأداء كامل",
        "subscribe_button": "اشترك",
        "monthly_label": "شهري",
        "yearly_label": "سنوي",
        "performance_guest_gate": "سجل دخول عشان تشوف أداءك",
        "streak_label": "أيام متتالية",
        "study_hours_label": "ساعات مذاكرة",
        "longest_streak_label": "أطول سلسلة",
        "score_progress_title": "تطور الدرجات",
        "weak_topics_title": "نقاط تحتاج مراجعة",
        "attempt_axis": "المحاولة",
        "percentage_axis": "النسبة",
        "add_friend": "إضافة صديق",
        "ask_a_question": "اسأل سؤال...",
        "average_score": "متوسط الدرجات",
        "bio": "نبذة عنك",
        "bio_placeholder": "اكتب نبذة بسيطة عنك...",
        "chat": "المحادثة",
        "chat_with_ai": "اسأل ذكّي",
        "chat_with_ai_subtitle": "اسأل عن أي شي بالملف",
        "close": "إغلاق",
        "co_host_badge": "مساعد",
        "confirm_kick": "متأكد تبي تطرد هذا المشارك؟",
        "connecting_to_room": "يتصل بالغرفة...",
        "current_streak": "أيام متتالية",
        "date": "التاريخ",
        "decline": "رفض",
        "duration_minutes_format": "المدة: %d دقيقة",
        "friend_request_sent": "تم إرسال طلب الصداقة ✓",
        "friend_requests": "طلبات الصداقة",
        "friends_count": "عدد الأصدقاء",
        "generate_quiz": "توليد اختبار",
        "generate_quiz_subtitle": "اختبر نفسك بأسئلة من الملف",
        "generating_quiz": "يولّد الاختبار...",
        "grant_permission": "منح صلاحية",
        "invalid_qr_code": "رمز QR غير صالح",
        "invite": "دعوة",
        "invite_from": "دعوة من %@",
        "invite_to_room": "دعوة للغرفة",
        "invited": "تمت الدعوة",
        "join": "انضمام",
        "join_by_code": "انضم بالكود",
        "join_voice": "انضم للصوت",
        "kicked_from_room": "تم طردك",
        "kicked_from_room_desc": "قام المضيف بطردك من هذه الغرفة",
        "leaderboard": "لوحة النتائج",
        "leave_voice": "غادر الصوت",
        "longest_streak": "أطول سلسلة",
        "mute": "كتم",
        "next_question": "السؤال التالي",
        "no_friends_yet": "ما عندك أصدقاء بعد",
        "num_questions_format": "عدد الأسئلة: %d",
        "participants": "المشاركين",
        "participants_count": "المشاركون (%d)",
        "paste_text_here": "الصق النص هنا...",
        "performance_empty": "ما فيه بيانات أداء بعد",
        "prepare_quiz": "تجهيز الاختبار",
        "privacy_settings": "إعدادات الخصوصية",
        "private_profile": "بروفايل خاص",
        "progress_over_time": "التطور عبر الوقت",
        "qr_scan_hint": "خلي صديقك يمسح هذا الرمز عشان يضيفك",
        "question_number": "السؤال %d من %d",
        "quiz_settings": "إعدادات الاختبار",
        "revoke_permission": "سحب الصلاحية",
        "room_code_placeholder": "أدخل كود الغرفة",
        "room_management": "إدارة الغرفة",
        "scan_qr_code": "امسح رمز QR",
        "score_percent": "النسبة %",
        "search_by_username": "ابحث باسم المستخدم",
        "search_results": "نتائج البحث",
        "session_hosted_by": "استضافة %@",
        "session_invites": "دعوات الجلسات",
        "share_room_code": "شارك كود الغرفة",
        "shared_summary": "الملخص المشترك",
        "show_archive_on_profile": "إظهار الأرشيف بالبروفايل",
        "show_friends_on_profile": "إظهار الأصدقاء بالبروفايل",
        "show_library_on_profile": "إظهار المكتبة بالبروفايل",
        "show_performance_on_profile": "إظهار الأداء بالبروفايل",
        "source_text": "نص المذاكرة",
        "start_quiz": "ابدأ الاختبار",
        "study": "المذاكرة",
        "total_attempts": "عدد المحاولات",
        "type_a_message": "اكتب رسالة...",
        "waiting_for_host": "بانتظار المضيف",
        "weak_topics": "نقاط تحتاج مراجعة",
        "your_score_format": "درجتك: %d من %d",
        "camera_permission_denied": "لازم تسمح باستخدام الكاميرا عشان تمسح رمز QR",
        "camera_unavailable": "الكاميرا غير متوفرة على هذا الجهاز",
        "open_settings": "افتح الإعدادات",
        "extracted_text": "نص الملف",
        "show_more": "عرض المزيد",
        "show_less": "عرض أقل",
        "chat_empty_title": "اسأل عن أي شي بالملف",
        "chat_empty_subtitle": "مثلًا: لخّص لي الفكرة الرئيسية، أو وضّح لي هذي النقطة",
        "is_typing": "%@ يكتب...",
        "are_typing": "أكثر من شخص يكتبون...",
        "add_text_to_board": "أضف نص للسبورة",
        "chat_closed": "المدرس قفل الشات مؤقتًا",
        "choose_file": "اختر ملف",
        "close_chat": "قفل الشات",
        "generate_summary": "ولّد الملخص",
        "open_chat": "فتح الشات",
        "share_summary_with_room": "شارك الملخص مع الطلاب",
        "start_solo_study": "ابدأ مذاكرة فردية",
        "start_solo_study_subtitle": "ملخص واختبار ودردشة ذكية",
        "summary_required_hint": "لازم تولّد الملخص قبل ما تقدر تبدأ الاختبار",
        "text_placeholder": "النص",
        "billing_period": "الفترة",
        "current_plan_badge": "باقتك الحالية",
        "restore_purchases": "استعادة المشتريات",
        "return_to_room": "الرجوع للغرفة",
    ]

    static let en: [String: String] = [
        "app_name": "Zakiy",
        "welcome_title": "Welcome to Zakiy",
        "welcome_subtitle": "AI-assisted collaborative study platform",
        "login": "Login",
        "signup": "Sign Up",
        "continue_guest": "Continue as Guest",
        "email": "Email",
        "password": "Password",
        "username": "Name",
        "education_level": "Education Level",
        "proficiency_level": "Proficiency",
        "already_have_account": "Have an account?",
        "no_account": "No account?",
        "home": "Home",
        "rooms": "Rooms",
        "library": "Library",
        "performance": "Performance",
        "settings": "Settings",
        "upload_pdf": "Upload PDF",
        "upload_pdf_subtitle": "Start a solo session from a new file",
        "solo_study": "Solo Study",
        "group_room": "Group Room",
        "group_room_subtitle": "Study with classmates in a live room",
        "live_lesson_subtitle": "Whiteboard and live group voice with your students",
        "room_type_classroom": "Live Lesson",
        "room_type_quiz": "Group Room",
        "summary": "Summary",
        "quiz": "Quiz",
        "chat_assistant": "Ask Zakiy",
        "create_room": "Create Room",
        "join_room": "I Have a Code",
        "room_code": "Room Code",
        "your_name": "Your Name",
        "logout": "Log Out",
        "language": "Language",
        "appearance": "Appearance",
        "appearance_system": "System",
        "appearance_light": "Light",
        "appearance_dark": "Dark",
        "subscription": "Subscription",
        "subscription_subtitle": "Manage your plan and subscription",
        "friends": "Friends",
        "friends_subtitle": "Add friends and view friend requests",
        "archive": "Archive",
        "archive_subtitle": "Past group study sessions",
        "current_plan": "Current Plan",
        "free_plan": "Free",
        "greeting_prefix": "Hi, %@",
        "home_greeting_subtitle": "Ready to study today?",
        "default_student_name": "Student",
        "loading": "Loading...",
        "error_generic": "Something went wrong, try again",
        "err_unexpected_response": "Unexpected server response",
        "err_server_status": "Server error (%d)",
        "ok": "OK",
        "cancel": "Cancel",
        "save": "Save",
        "add": "Add",
        "search": "Search",
        "delete": "Delete",
        "rename": "Rename",
        "edit": "Edit",
        "next": "Next",
        "finish": "Finish",
        "library_guest_gate": "Log in to see your library",
        "library_empty": "No saved books yet",
        "library_pick_empty": "No books in your library yet - save one from a solo session first",
        "pick_from_library": "Choose from your library",
        "add_book": "Add Book",
        "upload_from_device": "Upload from your device",
        "rename_book_title": "Rename Book",
        "book_title_placeholder": "Book title",
        "confirm_delete_book": "Are you sure you want to delete this book from your library?",
        "save_to_library_title": "Save to Your Library",
        "library_count_label": "%d books in library",
        "open_for_study": "Open for Study",
        "archive_guest_gate": "Log in to see your archive",
        "archive_empty": "No group sessions or lessons in your archive yet",
        "archive_host_label": "Host: %@",
        "friends_guest_gate": "Log in to add friends",
        "friends_empty": "You don't have any friends yet",
        "my_friends": "My Friends",
        "friends_count_label": "%d friends",
        "add_friend_section": "Add a Friend",
        "search_username_placeholder": "Search by username",
        "incoming_requests": "Incoming Requests",
        "outgoing_requests": "Sent Requests",
        "pending_label": "Pending",
        "accept": "Accept",
        "reject": "Reject",
        "remove_friend": "Remove",
        "confirm_remove_friend": "Are you sure you want to remove this friend?",
        "my_qr_code": "Your QR Code",
        "scan_qr": "Scan QR Code",
        "join_room_qr": "Room Join Code",
        "session_invites_heading": "📩 Session Invites",
        "session_invites_empty": "No new invites",
        "invite_from_prefix": "Invite from %@",
        "btn_join_now": "Join Now",
        "btn_dismiss_invite": "Dismiss",
        "profile": "Profile",
        "my_profile": "My Profile",
        "my_profile_subtitle": "Bio, school, and data privacy",
        "private_profile_badge": "Private",
        "private_profile_notice": "This profile is private - only its owner can see its details",
        "already_friends_badge": "Already friends",
        "incoming_request_notice": "Sent you a friend request - accept it from the Friends screen",
        "add_friend_button": "Add Friend",
        "stat_attempts": "Attempts",
        "stat_avg_score": "Avg Score",
        "stat_study_minutes": "Study Minutes",
        "stat_streak": "Day Streak",
        "profile_bio_section": "About You",
        "profile_bio_placeholder": "Write a short bio about yourself...",
        "school_name_placeholder": "Your school name",
        "private_profile_toggle": "Make my whole profile private",
        "private_profile_footer": "If enabled, no one can see anything on your profile besides your name, even friends.",
        "profile_sections_visibility_heading": "Visible on public profile",
        "guest_mode_label": "Guest Mode",
        "not_logged_in_label": "Not logged in",
        "edit_profile": "Edit Profile",
        "edit_profile_subtitle": "Name, phone number, and password",
        "phone_number": "Phone Number",
        "new_password": "New Password",
        "update_password": "Update Password",
        "profile_updated": "Profile updated ✓",
        "password_updated": "Password updated ✓",
        "start_study_button": "Start Studying",
        "start_quiz_button": "Start Quiz",
        "start_quiz_final_button": "Start Quiz for Everyone",
        "step_pick_file_title": "Pick a File",
        "step_summary_title": "Summary",
        "step_quiz_title": "Quiz",
        "next_generate_quiz": "Next: Generate Quiz",
        "shared_summary_section": "Shared Summary",
        "share_with_students": "Share with Students",
        "summary_shared_confirmation": "Summary shared with students ✓",
        "num_questions_label": "Questions: %d",
        "quiz_duration_label": "Duration: %d min",
        "invite_friends": "Invite Friends",
        "share_room_invite_text": "Join my room on Zakiy! Code: %@",
        "room_code_label": "Room Code: %@",
        "participants_title": "Participants",
        "participants_section": "Participants",
        "raised_hands_section": "Raised Hands",
        "raised_hands_count": "%d raised hands",
        "raise_hand": "Raise Hand",
        "lower_hand": "Lower Hand",
        "start_class": "Start Class",
        "waiting_for_teacher": "Waiting for the teacher to start",
        "chat_message_placeholder": "Type a message...",
        "grant_write_access": "Grant whiteboard write access",
        "revoke_write_access": "Revoke write access",
        "grant_content_access": "Grant upload & quiz access",
        "revoke_content_access": "Revoke access",
        "force_mute": "Force Mute",
        "kick": "Kick",
        "kicked_alert": "You were removed from the room",
        "err_invite_failed": "Couldn't send the invite",
        "invite_sent": "Sent ✓",
        "btn_invite_friend": "📨 Invite Friend",
        "invite_friend_no_friends": "You haven't added any friends yet",
        "top_results_heading": "🏆 Quiz Results",
        "status_still_solving": "Still solving...",
        "host_badge": "👑 Host",
        "permission_granted_badge": "Has permission",
        "storekit_unavailable": "Products aren't available yet (needs a direct Xcode Run, or an active App Store Connect account)",
        "plan_free": "Free",
        "plan_plus": "Plus",
        "plan_pro": "Pro",
        "plan_ultimate": "Ultimate",
        "plan_owner": "App Owner",
        "plan_plus_description": "8 library books, 5 daily sessions, 3 group rooms, 1 daily live lesson",
        "plan_pro_description": "15 library books, 10 daily sessions, 5 group rooms, 5 daily live lessons",
        "plan_ultimate_description": "30 library books, unlimited sessions & rooms, 8 daily live lessons, full archive & progress",
        "subscribe_button": "Subscribe",
        "monthly_label": "Monthly",
        "yearly_label": "Yearly",
        "performance_guest_gate": "Log in to see your performance",
        "streak_label": "Day Streak",
        "study_hours_label": "Study Hours",
        "longest_streak_label": "Longest Streak",
        "score_progress_title": "Score Progress",
        "weak_topics_title": "Needs Review",
        "attempt_axis": "Attempt",
        "percentage_axis": "Percentage",
        "add_friend": "Add Friend",
        "ask_a_question": "Ask a question...",
        "average_score": "Average Score",
        "bio": "Bio",
        "bio_placeholder": "Write a short bio about yourself...",
        "chat": "Chat",
        "chat_with_ai": "Ask Zakiy",
        "chat_with_ai_subtitle": "Ask anything about the file",
        "close": "Close",
        "co_host_badge": "Co-Host",
        "confirm_kick": "Are you sure you want to kick this participant?",
        "connecting_to_room": "Connecting to room...",
        "current_streak": "Current Streak",
        "date": "Date",
        "decline": "Decline",
        "duration_minutes_format": "Duration: %d min",
        "friend_request_sent": "Friend request sent ✓",
        "friend_requests": "Friend Requests",
        "friends_count": "Friends",
        "generate_quiz": "Generate Quiz",
        "generate_quiz_subtitle": "Test yourself with questions from the file",
        "generating_quiz": "Generating quiz...",
        "grant_permission": "Grant Permission",
        "invalid_qr_code": "Invalid QR code",
        "invite": "Invite",
        "invite_from": "Invite from %@",
        "invite_to_room": "Invite to Room",
        "invited": "Invited",
        "join": "Join",
        "join_by_code": "Join by Code",
        "join_voice": "Join Voice",
        "kicked_from_room": "You Were Removed",
        "kicked_from_room_desc": "The host removed you from this room",
        "leaderboard": "Leaderboard",
        "leave_voice": "Leave Voice",
        "longest_streak": "Longest Streak",
        "mute": "Mute",
        "next_question": "Next Question",
        "no_friends_yet": "You don't have any friends yet",
        "num_questions_format": "Questions: %d",
        "participants": "Participants",
        "participants_count": "Participants (%d)",
        "paste_text_here": "Paste text here...",
        "performance_empty": "No performance data yet",
        "prepare_quiz": "Prepare Quiz",
        "privacy_settings": "Privacy Settings",
        "private_profile": "Private Profile",
        "progress_over_time": "Progress Over Time",
        "qr_scan_hint": "Have your friend scan this code to add you",
        "question_number": "Question %d of %d",
        "quiz_settings": "Quiz Settings",
        "revoke_permission": "Revoke Permission",
        "room_code_placeholder": "Enter room code",
        "room_management": "Room Management",
        "scan_qr_code": "Scan QR Code",
        "score_percent": "Score %",
        "search_by_username": "Search by username",
        "search_results": "Search Results",
        "session_hosted_by": "Hosted by %@",
        "session_invites": "Session Invites",
        "share_room_code": "Share Room Code",
        "shared_summary": "Shared Summary",
        "show_archive_on_profile": "Show archive on profile",
        "show_friends_on_profile": "Show friends on profile",
        "show_library_on_profile": "Show library on profile",
        "show_performance_on_profile": "Show performance on profile",
        "source_text": "Study Text",
        "start_quiz": "Start Quiz",
        "study": "Study",
        "total_attempts": "Total Attempts",
        "type_a_message": "Type a message...",
        "waiting_for_host": "Waiting for host",
        "weak_topics": "Needs Review",
        "your_score_format": "Your score: %d/%d",
        "camera_permission_denied": "Camera access is needed to scan a QR code",
        "camera_unavailable": "Camera isn't available on this device",
        "open_settings": "Open Settings",
        "extracted_text": "File Text",
        "show_more": "Show More",
        "show_less": "Show Less",
        "chat_empty_title": "Ask anything about the file",
        "chat_empty_subtitle": "For example: summarize the main idea, or explain this point",
        "is_typing": "%@ is typing...",
        "are_typing": "Several people are typing...",
        "add_text_to_board": "Add text to the board",
        "chat_closed": "The teacher paused the chat",
        "choose_file": "Choose a File",
        "close_chat": "Close Chat",
        "generate_summary": "Generate Summary",
        "open_chat": "Open Chat",
        "share_summary_with_room": "Share summary with students",
        "start_solo_study": "Start Solo Study",
        "start_solo_study_subtitle": "Summary, quiz, and AI chat",
        "summary_required_hint": "You need to generate the summary before you can start the quiz",
        "text_placeholder": "Text",
        "billing_period": "Period",
        "current_plan_badge": "Your Current Plan",
        "restore_purchases": "Restore Purchases",
        "return_to_room": "Return to Room",
    ]
}
